import Arrow = require("./entities/Arrow");
import Target = require("./entities/Target");
import TargetRing = require("./entities/TargetRing");
import Scorer = require("./scoring/Scorer");
import LineBreakerHighestScorer = require("./scoring/LineBreakerHighestScorer");
import AccuracyStrategy = require("./accuracy/AccuracyStrategy");
import AverageAccuracyStrategy = require("./accuracy/AverageAccuracyStrategy");
import PrecisionStrategy = require("./precision/PrecisionStrategy");
import MeanRadiusPrecisionStrategy = require("./precision/MeanRadiusPrecisionStrategy");
import CEPPrecisionStrategy = require("./precision/CEPPrecisionStrategy");
import ExtremeSpreadPrecisionStrategy = require("./precision/ExtremeSpreadPrecisionStrategy");

let arrow = new Arrow(0, -20);
let arrow2 = new Arrow(0, 20);
let arrow3 = new Arrow(0, 0);
let arrow4 = new Arrow(15, 10);
let arrow5 = new Arrow(8, 7);
let target = new Target([new TargetRing(0, 10, 9), new TargetRing(10, 20, 8)]);
let scorer: Scorer = new LineBreakerHighestScorer();
let accuracy: AccuracyStrategy = new AverageAccuracyStrategy();
let precision: PrecisionStrategy = new MeanRadiusPrecisionStrategy();
target.putArrow(arrow);
target.putArrow(arrow2);
target.putArrow(arrow3);
target.putArrow(arrow4);
target.putArrow(arrow5);
console.log("Score: " + scorer.getScore(target));
console.log("Accuracy: " + accuracy.getAccuracy(target));
console.log("Precision: " + precision.getPrecision(target));